[package]
name = "website"
version = "0.1.0"
authors = ["addonovan <austin@addonovan.com>"]

[dependencies]
actix-web = "0.7"
handlebars = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
lazy_static = "1.0"
