[package]
name = "library"
version = "0.1.0"
authors = ["addonovan <austin@addonovan.com>"]

[dependencies]
actix-web = "0.7"
chrono = "0.4"
handlebars = "1.0"
serde = { version = "1.0", features = ["rc"] }
