use std::path::PathBuf;

/// Where did a cache item originate?
///
/// Was it generated from a file that was read, or was it processed and manually
/// inserted into the cache?
#[derive(PartialEq, Eq, Clone)]
pub enum Origin {

    /// The cache entry was generated by reading a file
    File(PathBuf),

//    /// The cache entry was manually placed into the cache
//    Manual,
}

impl Origin {

    /// Gets a string representation of this origin.
    pub fn as_str(&self) -> &'static str {
        use self::Origin::*;

        match self {
            File(_) => "File",
//            Manual => "Manual",
        }
    }

}
